apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  memberOf: [backstage]
