apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  memberOf: [backstage]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: thakursuraj509/first
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website # service, library
  owner: user:thakursuraj509 # Group/Users
  lifecycle: experimental # production, deprecated
  system: public-websites # System
  # subcomponentOf: test # Component
  # providesApis: [] # array of APIs 
  # consumesApis: [] # array of APIs
  # dependsOn: [] # array of Component/Resource
  # dependencyOf: [] # array of Component/Resource
  # dependsOn:
  #   - resource:default/artists-db
  # dependencyOf:
  #   - component:default/artist-web-lookup
  # providesApis:
  #   - artist-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public-websites
  description: System for managing public websites
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  owner: user:thakursuraj509
