apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage team
spec:
  type: team # business-unit, product-area, root [REQUIRED]
  profile:
    displayName: Backstage
    email: backstage@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  # parent: ops # Group (immediate parent group)
  children: [] # Group (immediate child groups) [REQUIRED]
  # members: [thakursuraj509] # User (users that are direct members of this group)
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  profile:
    displayName: Suraj Singh Thakur
    email: suraj@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [backstage] # Group [REQUIRED]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: thakursuraj509/first
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website # service, library [REQUIRED]
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  lifecycle: experimental # production, deprecated [REQUIRED]
  system: public-websites # System
  providesApis: 
    - auth-api
  dependsOn: 
    - resource:backstage-db
  # subcomponentOf: test # Component
  # providesApis: [] # API
  # consumesApis: [] # API
  # dependsOn: [] # Component/Resource (resource:default/artists-db)
  # dependencyOf: [] Component/Resource (component:default/artist-web-lookup)
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-db
  description: Stores backstage details
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: database # s3-bucket, kubernetes-cluster [REQUIRED]
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  lifecycle: experimental # production, deprecated [REQUIRED]
  system: public-websites # System
  # dependsOn: [] # Component/Resource (resource:default/artists-db)
  # dependencyOf: [] Component/Resource (component:default/artist-web-lookup)
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Verify user authentication status
spec:
  type: openapi # asyncapi, graphql, grpc [REQUIRED]
  lifecycle: experimental # production, deprecated [REQUIRED]
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  system: public-websites # System
  # apiProvidedBy: auth-service
  # definition: ... # [REQUIRED]
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
    ...
  # definition:
  #   $text: https://raw.githubusercontent.com/thakursuraj509/first/refs/heads/main/openapi/auth-api-spec.yaml   
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public-websites
  description: System for managing public websites
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  # type: product # service, feature-set
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  domain: backstage-domain  # Domain
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: backstage-domain
  description: Everything about backstage-domain
  tags:
    - java
spec:
  # type: product-area # product-group, bundle
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  # subdomainOf: audio-domain # Domain
---
# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: org-data
# spec:
#   type: url # file
#   # target: # str
#   targets:
#     - http://github.com/myorg/myproject/org-data-dump/catalog-info-staff.yaml
#     - http://github.com/myorg/myproject/org-data-dump/catalog-info-consultants.yaml
