apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  memberOf: [backstage]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: thakursuraj509/first
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website # service, package
  owner: user:thakursuraj509
  lifecycle: experimental # development, production
  system: public-websites
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public-websites
  description: System for managing public websites
  tags:
    - java
spec:
  owner: user:thakursuraj509
