apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage team
spec:
  type: team # business-unit, product-area, root [REQUIRED]
  profile:
    displayName: Backstage
    email: backstage@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  # parent: ops # Group (immediate parent group)
  children: [] # Group (immediate child groups) [REQUIRED]
  # members: [thakursuraj509] # User (users that are direct members of this group)
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  profile:
    displayName: Suraj Singh Thakur
    email: suraj@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [backstage] # Group [REQUIRED]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: thakursuraj509/first
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website # service, library [REQUIRED]
  owner: user:thakursuraj509 # Group/Users [REQUIRED]
  lifecycle: experimental # production, deprecated [REQUIRED]
  system: public-websites # System
  # subcomponentOf: test # Component
  # providesApis: [] # API
  # consumesApis: [] # API
  # dependsOn: [] # Component/Resource (resource:default/artists-db)
  # dependencyOf: [] Component/Resource (component:default/artist-web-lookup)
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: public-websites
  description: System for managing public websites
  tags:
    - java
  links:
    - url: https://github.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  owner: user:thakursuraj509
