apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: thakursuraj509
spec:
  memberOf: [backstage]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: thakursuraj509/first
spec:
  type: website
  owner: user:thakursuraj509
  lifecycle: experimental
